// Menu service - handles all menu-related Firebase operations (no auth required)
import { 
  doc, 
  setDoc, 
  updateDoc, 
  deleteDoc, 
  getDoc,
  onSnapshot,
  collection,
  query,
  orderBy
} from 'firebase/firestore';
import { appId } from '../config/firebase';
import { generateMenuId } from '../utils/menuId';

/**
 * Subscribe to a menu by ID (public access)
 * @param {Object} db - Firestore database instance
 * @param {string} menuId - Menu ID
 * @param {Function} callback - Callback function to receive menu data
 * @returns {Function} Unsubscribe function
 */
export const subscribeToMenu = (db, menuId, callback) => {
  if (!db || !menuId) {
    console.warn('Firestore or menuId not available');
    return () => {};
  }

  const menuRef = doc(db, `/artifacts/${appId}/menus`, menuId);
  
  return onSnapshot(menuRef, (snapshot) => {
    if (snapshot.exists()) {
      callback({
        id: snapshot.id,
        ...snapshot.data()
      });
    } else {
      callback(null); // Menu doesn't exist
    }
  }, (error) => {
    console.error("Error listening to menu:", error);
    callback(null);
  });
};

/**
 * Create a new menu with a specific ID
 * @param {Object} db - Firestore database instance
 * @param {string} menuId - Menu ID (generated by generateMenuId)
 * @param {string} name - Menu name
 * @param {Array<string>} recipeIds - Array of recipe IDs
 * @returns {Promise<void>}
 */
export const createMenu = async (db, menuId, name, recipeIds = []) => {
  if (!db || !menuId) throw new Error('Firestore or menuId not available');
  
  const menuRef = doc(db, `/artifacts/${appId}/menus`, menuId);
  await setDoc(menuRef, {
    name: name || 'Untitled Menu',
    recipeIds: recipeIds,
    createdAt: Date.now(),
    updatedAt: Date.now()
  });
};

/**
 * Get a menu by ID
 * @param {Object} db - Firestore database instance
 * @param {string} menuId - Menu ID
 * @returns {Promise<Object|null>} Menu data or null if not found
 */
export const getMenu = async (db, menuId) => {
  if (!db || !menuId) return null;
  
  const menuRef = doc(db, `/artifacts/${appId}/menus`, menuId);
  const menuDoc = await getDoc(menuRef);
  
  if (menuDoc.exists()) {
    return {
      id: menuDoc.id,
      ...menuDoc.data()
    };
  }
  return null;
};

/**
 * Update menu name
 * @param {Object} db - Firestore database instance
 * @param {string} menuId - Menu ID
 * @param {string} newName - New menu name
 */
export const updateMenuName = async (db, menuId, newName) => {
  if (!db || !menuId) throw new Error('Firestore or menuId not available');
  
  const menuRef = doc(db, `/artifacts/${appId}/menus`, menuId);
  await updateDoc(menuRef, { 
    name: newName.trim(),
    updatedAt: Date.now()
  });
};

/**
 * Update menu recipe IDs
 * @param {Object} db - Firestore database instance
 * @param {string} menuId - Menu ID
 * @param {Array<string>} recipeIds - Array of recipe IDs
 */
export const updateMenuRecipes = async (db, menuId, recipeIds) => {
  if (!db || !menuId) throw new Error('Firestore or menuId not available');
  
  const menuRef = doc(db, `/artifacts/${appId}/menus`, menuId);
  await updateDoc(menuRef, { 
    recipeIds: recipeIds,
    updatedAt: Date.now()
  });
};

/**
 * Add recipe to a menu
 * @param {Object} db - Firestore database instance
 * @param {string} menuId - Menu ID
 * @param {string} recipeId - Recipe ID to add
 */
export const addRecipeToMenu = async (db, menuId, recipeId) => {
  if (!db || !menuId) throw new Error('Firestore or menuId not available');
  
  const menuRef = doc(db, `/artifacts/${appId}/menus`, menuId);
  const menuDoc = await getDoc(menuRef);
  
  if (menuDoc.exists()) {
    const menuData = menuDoc.data();
    if (!menuData.recipeIds.includes(recipeId)) {
      await updateDoc(menuRef, {
        recipeIds: [...menuData.recipeIds, recipeId],
        updatedAt: Date.now()
      });
    }
  }
};

/**
 * Remove recipe from a menu
 * @param {Object} db - Firestore database instance
 * @param {string} menuId - Menu ID
 * @param {string} recipeId - Recipe ID to remove
 */
export const removeRecipeFromMenu = async (db, menuId, recipeId) => {
  if (!db || !menuId) throw new Error('Firestore or menuId not available');
  
  const menuRef = doc(db, `/artifacts/${appId}/menus`, menuId);
  const menuDoc = await getDoc(menuRef);
  
  if (menuDoc.exists()) {
    const menuData = menuDoc.data();
    await updateDoc(menuRef, {
      recipeIds: menuData.recipeIds.filter(id => id !== recipeId),
      updatedAt: Date.now()
    });
  }
};

/**
 * Delete a menu
 * @param {Object} db - Firestore database instance
 * @param {string} menuId - Menu ID
 */
export const deleteMenu = async (db, menuId) => {
  if (!db || !menuId) throw new Error('Firestore or menuId not available');
  
  const menuRef = doc(db, `/artifacts/${appId}/menus`, menuId);
  await deleteDoc(menuRef);
};

// ===== SPACE-BASED MENU FUNCTIONS =====

/**
 * Save the current menu (today's menu) for a space
 * @param {Object} db - Firestore database instance
 * @param {string} spaceId - Space ID
 * @param {Array<string>} recipeIds - Array of recipe IDs
 */
export const saveCurrentMenu = async (db, spaceId, recipeIds) => {
  if (!db || !spaceId) return;
  
  try {
    const currentMenuRef = doc(db, `/artifacts/${appId}/spaces/${spaceId}/data`, 'currentMenu');
    await setDoc(currentMenuRef, {
      recipeIds: recipeIds || [],
      updatedAt: Date.now()
    }, { merge: true });
  } catch (e) {
    console.error("Error saving current menu:", e);
    throw e;
  }
};

/**
 * Get the current menu for a space
 * @param {Object} db - Firestore database instance
 * @param {string} spaceId - Space ID
 * @returns {Promise<Array<string>>} Array of recipe IDs
 */
export const getCurrentMenu = async (db, spaceId) => {
  if (!db || !spaceId) return [];
  
  try {
    const currentMenuRef = doc(db, `/artifacts/${appId}/spaces/${spaceId}/data`, 'currentMenu');
    const currentMenuDoc = await getDoc(currentMenuRef);
    
    if (currentMenuDoc.exists()) {
      const data = currentMenuDoc.data();
      return data.recipeIds || [];
    }
    return [];
  } catch (e) {
    console.error("Error getting current menu:", e);
    return [];
  }
};

/**
 * Subscribe to current menu changes for a space
 * @param {Object} db - Firestore database instance
 * @param {string} spaceId - Space ID
 * @param {Function} callback - Callback function to receive recipe IDs
 * @returns {Function} Unsubscribe function
 */
export const subscribeToCurrentMenu = (db, spaceId, callback) => {
  if (!db || !spaceId) {
    console.warn('Firestore or spaceId not available');
    return () => {};
  }

  const currentMenuRef = doc(db, `/artifacts/${appId}/spaces/${spaceId}/data`, 'currentMenu');
  
  return onSnapshot(currentMenuRef, (snapshot) => {
    if (snapshot.exists()) {
      const data = snapshot.data();
      callback(data.recipeIds || []);
    } else {
      callback([]);
    }
  }, (error) => {
    console.error("Error listening to current menu:", error);
    callback([]);
  });
};

/**
 * Subscribe to all saved menus for a space
 * @param {Object} db - Firestore database instance
 * @param {string} spaceId - Space ID
 * @param {Function} callback - Callback function to receive menus array
 * @returns {Function} Unsubscribe function
 */
export const subscribeToMenus = (db, spaceId, callback) => {
  if (!db || !spaceId) {
    console.warn('Firestore or spaceId not available');
    return () => {};
  }

  const menusRef = collection(db, `/artifacts/${appId}/spaces/${spaceId}/menus`);
  const q = query(menusRef, orderBy('createdAt', 'desc'));
  
  return onSnapshot(q, (snapshot) => {
    const menus = snapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }));
    callback(menus);
  }, (error) => {
    console.error("Error listening to menus:", error);
    callback([]);
  });
};

/**
 * Create a new menu for a space
 * @param {Object} db - Firestore database instance
 * @param {string} spaceId - Space ID
 * @param {string} name - Menu name
 * @param {Array<string>} recipeIds - Array of recipe IDs
 * @returns {Promise<string>} The created menu ID
 */
export const createMenuForSpace = async (db, spaceId, name, recipeIds = []) => {
  if (!db || !spaceId) throw new Error('Firestore or spaceId not available');
  
  const menuId = generateMenuId();
  const menuRef = doc(db, `/artifacts/${appId}/spaces/${spaceId}/menus`, menuId);
  
  await setDoc(menuRef, {
    name: name || 'Untitled Menu',
    recipeIds: recipeIds,
    createdAt: Date.now(),
    updatedAt: Date.now()
  });
  
  return menuId;
};

/**
 * Add recipe to a menu in a space
 * @param {Object} db - Firestore database instance
 * @param {string} spaceId - Space ID
 * @param {string} menuId - Menu ID
 * @param {string} recipeId - Recipe ID to add
 */
export const addRecipeToMenuInSpace = async (db, spaceId, menuId, recipeId) => {
  if (!db || !spaceId || !menuId) throw new Error('Firestore, spaceId, or menuId not available');
  
  const menuRef = doc(db, `/artifacts/${appId}/spaces/${spaceId}/menus`, menuId);
  const menuDoc = await getDoc(menuRef);
  
  if (menuDoc.exists()) {
    const menuData = menuDoc.data();
    if (!menuData.recipeIds.includes(recipeId)) {
      await updateDoc(menuRef, {
        recipeIds: [...menuData.recipeIds, recipeId],
        updatedAt: Date.now()
      });
    }
  }
};

/**
 * Update menu name in a space
 * @param {Object} db - Firestore database instance
 * @param {string} spaceId - Space ID
 * @param {string} menuId - Menu ID
 * @param {string} newName - New menu name
 */
export const updateMenuNameInSpace = async (db, spaceId, menuId, newName) => {
  if (!db || !spaceId || !menuId) throw new Error('Firestore, spaceId, or menuId not available');
  
  const menuRef = doc(db, `/artifacts/${appId}/spaces/${spaceId}/menus`, menuId);
  await updateDoc(menuRef, { 
    name: newName.trim(),
    updatedAt: Date.now()
  });
};

/**
 * Delete a menu from a space
 * @param {Object} db - Firestore database instance
 * @param {string} spaceId - Space ID
 * @param {string} menuId - Menu ID
 */
export const deleteMenuFromSpace = async (db, spaceId, menuId) => {
  if (!db || !spaceId || !menuId) throw new Error('Firestore, spaceId, or menuId not available');
  
  const menuRef = doc(db, `/artifacts/${appId}/spaces/${spaceId}/menus`, menuId);
  await deleteDoc(menuRef);
};
